# In Class Notebook, Week 05

You can click on the GitHub URL of this notebook to access the file in near-real time: https://github.com/UIUC-iSchool-DataViz/is445_obuobg_spring2025/blob/master/week05/inClass_week05.ipynb 

Or you can copy-paste into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import ipywidgets

In [2]:
islider = ipywidgets.IntSlider(min=0,max=10,step=1, orientation='vertical')

In [3]:
islider

IntSlider(value=0, max=10, orientation='vertical')

In [4]:
cp = ipywidgets.ColorPicker()

In [5]:
cp

ColorPicker(value='black')

In [6]:
ipywidgets.link( (cp,'value'), (islider.style, 'handle_color') )

In [7]:
class MyObject():
    name = 'unnamed'
    age = 0

In [8]:
my_obj = MyObject()

In [9]:
my_obj.name, my_obj.age

('unnamed', 0)

In [10]:
my_obj.name = "Bob"
my_obj.age = 47

In [11]:
my_obj.name, my_obj.age

('Bob', 47)

In [12]:
import traitlets

In [14]:
# class MyObject():
#     name = 'unnamed'
#     age = 0

class MyTraitletsObject(traitlets.HasTraits):
    name = traitlets.Unicode('unnamed') # traitlets-specific way of saying "string"
    age = traitlets.Int(0) # traitlets-specific way of saying "int"

In [15]:
my_t_obj = MyTraitletsObject()

In [16]:
my_t_obj.name, my_t_obj.age

('unnamed', 0)

In [17]:
my_t_obj.name = 'Bob'
my_t_obj.age = 47

In [18]:
my_t_obj.name, my_t_obj.age

('Bob', 47)

In [19]:
def name_changed(change):
    print(change)

my_t_obj.observe(name_changed, ['name']) # run function whenever name changes

In [20]:
my_t_obj.name = 'Linda'

{'name': 'name', 'old': 'Bob', 'new': 'Linda', 'owner': <__main__.MyTraitletsObject object at 0x11701c9e0>, 'type': 'change'}


In [21]:
def name_changed2(change):
    #print(change)
    print("Hello, my name is", change['new'], 'and I am', change['owner'].age, 'years old.')

my_t_obj.observe(name_changed2, ['name']) # run function whenever name changes

In [22]:
my_t_obj.name = 'Bob'

{'name': 'name', 'old': 'Linda', 'new': 'Bob', 'owner': <__main__.MyTraitletsObject object at 0x11701c9e0>, 'type': 'change'}
Hello, my name is Bob and I am 47 years old.


In [23]:
my_t_obj.unobserve(name_changed, ['name'])

In [24]:
my_t_obj.name = 'Linda'

Hello, my name is Linda and I am 47 years old.


In [26]:
# include a print statement for changing the age
def age_changed(change):
    #print("Hello, my name is", change['new'], 'and I am', change['owner'].age, 'years old.')
    print("Hello, my name is", change['owner'].name, 'and I am', change['new'], 'years old.')

my_t_obj.observe(age_changed, ['age'])    

In [27]:
my_t_obj.age = 45

Hello, my name is Linda and I am 45 years old.


In [30]:
my_t_obj.name = 'Louise'; my_t_obj.age = 8

Hello, my name is Louise and I am 8 years old.


In [31]:
my_t_obj.name, my_t_obj.age = 'Linda', 45

Hello, my name is Linda and I am 8 years old.
Hello, my name is Linda and I am 45 years old.


## Intro to bqplot

In [1]:
import bqplot

In [2]:
import numpy as np

In [3]:
# 1. Make/read in data
x = np.arange(100) 
y = np.random.random(100)

In [6]:
#x

In [7]:
#y

In [8]:
# 2. Scales
bqplot.LinearScale?

Init signature: bqplot.LinearScale(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
A linear scale.

An affine mapping from a numerical domain to a numerical range.

Attributes
----------
min: float or None (default: None)
    if not None, min is the minimal value of the domain
max: float or None (default: None)
    if not None, max is the maximal value of the domain
rtype: string (class-level attribute)
    This attribute should not be modified. The range type of a linear
    scale is numerical.
dtype: type (class-level attribute)
    the associated data type / domain type
precedence: int (class-level attribute, default_value=2)
    attribute used to determine which scale takes precedence in cases when
    two or more scales have the same rtype and dtype.
    default_value is 2 because for the same range and domain types,
    LinearScale should take precedence.
stabilized: bool (default: False)
    if set to False, the domain of the scale is tied to the data range
    if 

In [9]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [10]:
# 3. Axis 
bqplot.Axis?

Init signature: bqplot.Axis(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
A line axis.

A line axis is the visual representation of a numerical or date scale.

Attributes
----------
icon: string (class-level attribute)
    The font-awesome icon name for this object.
axis_types: dict (class-level attribute)
    A registry of existing axis types.
orientation: {'horizontal', 'vertical'}
    The orientation of the axis, either vertical or horizontal
side: {'bottom', 'top', 'left', 'right'} or None (default: None)
    The side of the axis, either bottom, top, left or right.
label: string (default: '')
    The axis label
tick_format: string or None (default: '')
    The tick format for the axis, for dates use d3 string formatting.
scale: Scale
    The scale represented by the axis
num_ticks: int or None (default: None)
    If tick_values is None, number of ticks
tick_values: numpy.ndarray or None (default: None)
    Tick values for the axis
offset: dict (default: {})
    Cont

In [11]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [12]:
# 4. Marks (sometimes this swaps with Axis)
bqplot.Lines?

Init signature: bqplot.Lines(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
Lines mark.

In the case of the Lines mark, scales for 'x' and 'y' MUST be provided.

Attributes
----------
icon: string (class-level attribute)
    Font-awesome icon for the respective mark
name: string (class-level attribute)
    User-friendly name of the mark
colors: list of colors (default: CATEGORY10)
    List of colors of the Lines. If the list is shorter than the number
    of lines, the colors are reused.
close_path: bool (default: False)
    Whether to close the paths or not.
fill: {'none', 'bottom', 'top', 'inside', 'between'}
    Fill in the area defined by the curves
fill_colors: list of colors (default: [])
    Fill colors for the areas. Defaults to stroke-colors when no
    color provided
opacities: list of floats (default: [])
    Opacity for the  lines and patches. Defaults to 1 when the list is too
    short, or the element of the list is set to None.
fill_opacities: list of floa

In [13]:
lines = bqplot.Lines(x=x,y=y, scales = {'x':x_sc, 'y':y_sc})

In [14]:
# 5. interactivity would happen around here

In [15]:
# 6. put it all together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [16]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

One more time all together:

In [17]:
# 1. Make/read in data
x = np.arange(100) 
y = np.random.random(100)

# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. Axis
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

# 4. Mark(s)
lines = bqplot.Lines(x=x,y=y, scales = {'x':x_sc, 'y':y_sc})

# 5. interactivity would happen around here

# 6. put it all together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale()), Axis(label='Y Value', orientation='vertical', scale=L…

In [18]:
bqplot.interacts.PanZoom?

Init signature: bqplot.interacts.PanZoom(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
An interaction to pan and zoom wrt scales.

Attributes
----------
allow_pan: bool (default: True)
    Toggle the ability to pan.
allow_zoom: bool (default: True)
    Toggle the ability to zoom.
scales: Dictionary of lists of Scales (default: {})
    Dictionary with keys such as 'x' and 'y' and values being the scales in
    the corresponding direction (dimensions) which should be panned or
    zoomed.
Init docstring: Public constructor
File:           /opt/anaconda3/envs/DataViz2/lib/python3.10/site-packages/bqplot/interacts.py
Type:           MetaHasTraits
Subclasses:     

In [20]:
# 1. Make/read in data
x = np.arange(100) 
y = np.random.random(100)

# 2. Scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. Axis
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

# 4. Mark(s)
lines = bqplot.Lines(x=x,y=y, scales = {'x':x_sc, 'y':y_sc})

# 5. interactivity would happen around here
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

# 6. put it all together into a figure
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale()), Axis(label='Y Value', orientation='vertical', scale=L…

In [21]:
# 1. Make more random data
x = np.random.random(100)
y = np.random.random(100)

In [22]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [23]:
# 3. axis
ax_x = bqplot.Axis(scale=x_sc, label='X')
ax_y = bqplot.Axis(scale=y_sc, label='Y', orientation='vertical')

In [24]:
# 4. marks
bqplot.Scatter?

Init signature: bqplot.Scatter(*args: 't.Any', **kwargs: 't.Any') -> 't.Any'
Docstring:     
Scatter mark.

In the case of the Scatter mark, scales for 'x' and 'y' MUST be provided.
The scales of other data attributes are optional. In the case where another
data attribute than 'x' or 'y' is provided but the corresponding scale is
missing, the data attribute is ignored.

Attributes
----------
icon: string (class-level attribute)
    Font-awesome icon for that mark
name: string (class-level attribute)
    User-friendly name of the mark
marker: {'circle', 'cross', 'diamond', 'square', 'triangle-down', 'triangle-up', 'arrow', 'rectangle', 'ellipse'}
    Marker shape
colors: list of colors (default: ['steelblue'])
    List of colors of the markers. If the list is shorter than the number
    of points, the colors are reused.
default_colors: Deprecated
    Same as `colors`, deprecated as of version 0.8.4
fill: Bool (default: True)
    Whether to fill the markers or not
stroke: Color or None (

In [25]:
scatters = bqplot.Scatter(x=x,y=y, scales={'x':x_sc, 'y':y_sc})

In [26]:
# 5. interactivity?

In [27]:
# 6. figure
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y])
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [32]:
# 1. Make more random data
x = np.random.random(100)
y = np.random.random(100)

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
ax_x = bqplot.Axis(scale=x_sc, label='X')
ax_y = bqplot.Axis(scale=y_sc, label='Y', orientation='vertical')

# 4. marks
scatters = bqplot.Scatter(x=x,y=y, scales={'x':x_sc, 'y':y_sc})

# 5. interactivity?
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

# 6. figure
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale()), Axis(label='Y', orientation='vertical', scale=LinearScale()…

In [31]:
#bqplot.interacts.FastIntervalSelector?

In [36]:
selector.selected

array([0.46335852, 0.67220538])

In [35]:
scatters.selected_style = {'fill':'red', 'stroke':'yellow'}

## 2D Heatmap (random data)

In [43]:
# 1. data
data = np.random.random((10,10))
#data.shape

# 2. scales
col_sc = bqplot.ColorScale()
#bqplot.ColorScale?

# 3. axis

# 4. mark
#bqplot.GridHeatMap?
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactivity

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.02290…

In [46]:
# 1. data
data = np.random.random((10,10))
#data.shape

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()
#bqplot.ColorScale?

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
#bqplot.GridHeatMap?
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. interactivity

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(label='C…

In [47]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(label='C…

In [51]:
heat_map.selected

array([[4, 3]])

In [52]:
import ipywidgets

In [53]:
myLabel = ipywidgets.Label()

In [54]:
myLabel.value

''

In [58]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        myLabel.value = str(i) + ',' + str(j)
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(label='C…

In [62]:
# 1. data
data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    #print(change)
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        #myLabel.value = str(i) + ',' + str(j)
        myLabel.value = 'Data value = ' + str(data[i,j])
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig

# 7. dashboard it
dashboard = ipywidgets.VBox([myLabel, fig])
dashboard

## 3d random data heatmap

In [67]:
data3d = np.random.random((10,10,20))

In [68]:
data3d.shape

(10, 10, 20)

In [69]:
# 1. data
##data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:]))
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig

# 7. dashboard it
dashboard = ipywidgets.VBox([myLabel, fig])
dashboard

In [79]:
heat_map.selected

array([[6, 5]])

In [80]:
i,j = heat_map.selected[0] #0, 6 # hard code

In [81]:
data3d[i,j,:] # 1. data for histogram

array([0.45620668, 0.70036455, 0.48694533, 0.46400419, 0.74148338,
       0.82281054, 0.97832207, 0.05267568, 0.47081541, 0.24431269,
       0.65004576, 0.75324808, 0.51024158, 0.41400908, 0.25927807,
       0.55810438, 0.00509994, 0.58051639, 0.85538119, 0.20986513])

In [82]:
# 2. scales for histogram
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. axis for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value for 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

In [83]:
#bqplot.Hist?

In [84]:
# 4. mark for histogram
hist = bqplot.Hist(sample=data3d[i,j,:], scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [85]:
# 5. interactions for histogram

# 6. figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value for 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', ori…

In [86]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [87]:
hist.sample

array([0.45620668, 0.70036455, 0.48694533, 0.46400419, 0.74148338,
       0.82281054, 0.97832207, 0.05267568, 0.47081541, 0.24431269,
       0.65004576, 0.75324808, 0.51024158, 0.41400908, 0.25927807,
       0.55810438, 0.00509994, 0.58051639, 0.85538119, 0.20986513])

In [88]:
# 1. data
##data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:])) # changing value trait of myLabel
        hist.sample = data3d[i,j,:] # changing sample trait of histogram mark
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])

# 7. dashboard it
dashboard = ipywidgets.VBox([myLabel, fig])
dashboard

In [89]:
# 1. data
##data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:])) # changing value trait of myLabel
        hist.sample = data3d[i,j,:] # changing sample trait of histogram mark
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])

# 7. dashboard it
#dashboard = ipywidgets.VBox([myLabel, fig])
figures = ipywidgets.HBox([fig, figh])
dashboard = ipywidgets.VBox([myLabel, figures])
dashboard

In [92]:
# 1. data
##data = np.random.random((10,10))

# 2. scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale() # ordered bin numbers
y_sc = bqplot.OrdinalScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Column Bin')
y_ax = bqplot.Axis(scale=y_sc, label='Row Bin', orientation='vertical')
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. mark
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc}, 
                             interactions={'click':'select'}, 
                             anchor_style={'fill':'magenta'}
                             )

# 5. interactivity
def on_selected(change):
    if len(change['owner'].selected) == 1: # in this case, allow user to update plot
        i,j = change['owner'].selected[0]
        myLabel.value = 'Data value (sum) = ' + str(np.sum(data3d[i,j,:])) # changing value trait of myLabel
        hist.sample = data3d[i,j,:] # changing sample trait of histogram mark
        
heat_map.observe(on_selected, 'selected')

# 6. all together in a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])

# 7. dashboard it
figures = ipywidgets.HBox([fig, figh])
dashboard = ipywidgets.VBox([myLabel, figures])
fig.layout.min_width = '500px'
figh.layout.min_width = '500px'
dashboard